default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  username: <%= ENV["USER" ] %>
  password: <%= ENV["DATABASE_PASSWORD" ] %>



development:
  <<: *default
  database: anpe_development
  host: localhost

test:
  <<: *default
  database: anpe_test

staging:
  <<: *default
  database: anpe_staging

production:
  <<: *default
  database: anpe_production
